export const PRICING = {
  // Individual Support Package Prices
  BASIC_PACKAGE_PRICE:
    Number(process.env.NEXT_PUBLIC_BASIC_PACKAGE_PRICE) || 270,
  STANDARD_PACKAGE_PRICE:
    Number(process.env.NEXT_PUBLIC_STANDARD_PACKAGE_PRICE) || 390,
  COMPREHENSIVE_PACKAGE_PRICE:
    Number(process.env.NEXT_PUBLIC_COMPREHENSIVE_PACKAGE_PRICE) || 500,
  EXTENSION_PRICE_PER_WEEK:
    Number(process.env.NEXT_PUBLIC_EXTENSION_PRICE_PER_WEEK) || 150,

  // Consultation Prices
  CONSULTATION_PRICE: Number(process.env.NEXT_PUBLIC_CONSULTATION_PRICE) || 150,
  RETURNING_CONSULTATION_PRICE:
    Number(process.env.NEXT_PUBLIC_RETURNING_CONSULTATION_PRICE) || 100,
} as const;
